### PR TITLE
SignUp Login Linking and Shared Preferences added

### LINKED ISSUE #87: Linking Successful Signup and Login Screens
### Describe the bug
After successful Signup user should be taken to Login Screen. But the app shows the screen as shown in the screenshot.

Same happens with the Logi Screen User should be taken to home but the  app shows the screen as shown in the screenshot.

### PR DESCRIPTION
**Pull request by Hard-Coder05**
### Description

Linked Successful Signup and Login screens. Added shared preferences in the required places.

**Type of Change:** (Delete irrelevant options)
- Code

**Code/Quality Assurance Only** (Delete irrelevant options)

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?

tested on my local device

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] I have added one/more required dependencies
- [x] I have formatted the code using dart format (dartfmt)

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: lib/main.dart [hunk 1]
```diff
@@ -14,16 +17,20 @@ void main() async {
...
-      home: BlocProvider(
-        create: (context) => LoginCubit(APILoginRepository()),
-        child: LoginScreen(),
-      ),
+      home: token != null
+          ? HomeScreen()
+          : BlocProvider(
+              create: (context) => LoginCubit(APILoginRepository()),
+              child: LoginScreen(),
+            ),
```
Comment (werainkhatri) [inline lib/main.dart]: This is supposed to be done in splash screen. First make that, then do this. For now, leave it as it was.

File: lib/screens/login/login.dart [hunk 2]
```diff
@@ -22,13 +27,21 @@ class LoginScreen extends StatelessWidget {
 
   @override
   Widget build(BuildContext context) {
+    SharedPreferences sharedPreferences = sl.get<SharedPreferences>();
```
Comment (werainkhatri) [inline lib/screens/login/login.dart]: since this variable is needed only when LoginSuccess, declare it where it is used.

File: lib/screens/login/login.dart [hunk 3]
```diff
@@ -22,13 +27,21 @@ class LoginScreen extends StatelessWidget {
...
     return Scaffold(
       resizeToAvoidBottomInset: false,
       body: BlocConsumer<LoginCubit, LoginState>(
         listener: (context, state) async {
           if (state is LoginSuccess) {
+            await sharedPreferences.setString(S.tokenKeySharedPreferences, state.token);
             await Future.delayed(Duration(seconds: 1));
```
Comment (werainkhatri) [inline lib/screens/login/login.dart]: 1. no need for this.
2. add a snackbar to tell the user login was successful.

File: lib/screens/signup/signup.dart [hunk 4]
```diff
@@ -34,7 +34,15 @@ class SignupScreen extends StatelessWidget {
           if (state is SignupError) {
             Scaffold.of(context).showSnackBar(SnackBar(content: Text(state.message)));
           } else if (state is SignupSuccess) {
-            // TODO
+            Navigator.pushReplacement(
```
Comment (werainkhatri) [inline lib/screens/signup/signup.dart:38]: Add a snackbar here telling the user that signup was successful.

**Review by werainkhatri — CHANGES_REQUESTED** [review]
Things to do:
1. _buildSuccess() in both SignupScreen and LoginScreen are unaligned with our design, so remove them.
2. When success occurs, 
UI (builder): return the initial page itself.
Logic (listener): don't future.wait.

File: lib/screens/signup/signup.dart (hunk 4 above)
Comment (Hard-Coder05) [reply lib/screens/signup/signup.dart:38]: done

File: lib/screens/login/login.dart (hunk 3 above)
Comment (Hard-Coder05) [reply lib/screens/login/login.dart]: done

File: lib/screens/login/login.dart (hunk 2 above)
Comment (Hard-Coder05) [reply lib/screens/login/login.dart]: removes this for now

File: lib/main.dart (hunk 1 above)
Comment (Hard-Coder05) [reply lib/main.dart]: removed this for now

**Comment by Hard-Coder05** [comment]
> Things to do:
> 
> 1. _buildSuccess() in both SignupScreen and LoginScreen are unaligned with our design, so remove them.
> 2. When success occurs,
>    UI (builder): return the initial page itself.
>    Logic (listener): don't future.wait.

done

File: lib/screens/login/login.dart (hunk 2 above)
Comment (werainkhatri) [reply lib/screens/login/login.dart]: Then when are you planning to do this?
I would say, move this to cubit and call this after you get the token, before emitting LoginSuccess.

**Review by werainkhatri — CHANGES_REQUESTED** [review]
Just add the sharedpreferences line in the cubit. also pull the latest changes from main

**Comment by Hard-Coder05** [comment]
@werainkhatri Done from my side!

File: lib/screens/login/login.dart (hunk 2 above)
Comment (Hard-Coder05) [reply lib/screens/login/login.dart]: Done!

File: lib/screens/login/cubit/login_cubit.dart [hunk 5]
```diff
@@ -15,6 +17,8 @@ class LoginCubit extends Cubit<LoginState> {
     try {
       emit(LoginLoading());
       String token = await _loginRepository.login(email, password);
+      SharedPreferences sharedPreferences = sl.get<SharedPreferences>();
+      await sharedPreferences.setString(S.tokenKeySharedPreferences, token);
```
Comment (werainkhatri) [inline lib/screens/login/cubit/login_cubit.dart]:
```suggestion
      await sl.get<SharedPreferences>().setString(S.tokenKeySharedPreferences, token);
```

File: lib/screens/login/login.dart [hunk 6]
```diff
@@ -1,6 +1,7 @@
 import 'package:ecellapp/core/res/colors.dart';
 import 'package:ecellapp/core/res/dimens.dart';
 import 'package:ecellapp/core/res/strings.dart';
+import 'package:ecellapp/core/utils/injection.dart';
```
Comment (werainkhatri) [inline lib/screens/login/login.dart]:
```suggestion
```

File: lib/screens/login/login.dart [hunk 7]
```diff
@@ -14,6 +15,7 @@ import 'package:flutter/gestures.dart';
 import 'package:flutter/material.dart';
 import 'package:flutter_bloc/flutter_bloc.dart';
 import 'package:google_fonts/google_fonts.dart';
+import 'package:shared_preferences/shared_preferences.dart';
```
Comment (werainkhatri) [inline lib/screens/login/login.dart]:
```suggestion
```

**Review by werainkhatri — CHANGES_REQUESTED** [review]
Final changes

File: lib/screens/login/login.dart (hunk 7 above)
Comment (Hard-Coder05) [reply lib/screens/login/login.dart]: done

File: lib/screens/login/login.dart (hunk 6 above)
Comment (Hard-Coder05) [reply lib/screens/login/login.dart]: done

File: lib/screens/login/cubit/login_cubit.dart (hunk 5 above)
Comment (Hard-Coder05) [reply lib/screens/login/cubit/login_cubit.dart]: done

**Review by werainkhatri — APPROVED** [review]
