### PR TITLE
bugfix: Events cubit 🚨

### LINKED ISSUE #108: Broken Events Cubit 🚨
### Describe the bug

Cubit doesn't redirect to other states after initial i.ie. Cubit struck at EventsInitial 
Method to return list is non-functional. List<event> thrown is empty.

### To Reproduce

1. Go to spashscreen and change the login to Events
2. Change or place Log.d() with the size of list<event> as a parameter(events_repository.dart) and state name in events.dart
3. Save and run 

### Expected behavior
A clear and concise description of what you expected to happen:
A smooth flow of service to display the size as 1 (based on json given ) and display on screen. 

### Additional context
Screenshot from 2021-02-18 03-40-14

### PR DESCRIPTION
**Pull request by TreavVasu**
### Description

Fixes Error and poor tested code in #72 #48 

**Type of Change:** (Delete irrelevant options)
- Code
- Testing

**Code/Quality Assurance Only** (Delete irrelevant options)

- Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged
- [ ] I have added one/more required dependencies
- [x] I have formatted the code using dart format (dartfmt)

**Code/Quality Assurance**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

**Mention the dependencies/packages/plugins that have been added (if any)**

### CODE REVIEW

File: lib/screens/events/events.dart [hunk 1]
```diff
@@ -12,29 +13,30 @@ class EventsScreen extends StatefulWidget {
...
+          builder: (context, state) {
+            if (state is EventsInitial) {
+              return _buildInitial();
+            } else if (state is EventsSuccess) {
+              return _buildSuccess(context, state.json);
+            } else if (state is EventsLoading) {
+              return _buildLoading();
+            } else {
+              Log.e(tag: "EventsState", message: "State now is EventsError reached");
+              return Container(); // TODO the user should be shown the error on screen instead of a snackbar, and a retry button.
```
Comment (werainkhatri) [inline lib/screens/events/events.dart:36]: update on the retry screen?

File: lib/screens/events/events_repository.dart [hunk 2]
```diff
@@ -47,8 +47,8 @@ class FakeEventsRepository implements EventsRepository {
           }
         ]
       };
-      List<Event> events;
-      (json["data"] as List).map((e) => events.add(Event.fromJson(e)));
+      List<Event> events = List();
+      (json["data"] as List).map((e) => events.add(Event.fromJson(e))).toList();
```
Comment (werainkhatri) [inline lib/screens/events/events_repository.dart]: 🔴 
`map` is different from `forEach`. Please read about them.
1. Map
```suggestion
      List<Event> events = (json["data"] as List).map((e) => events.add(Event.fromJson(e))).toList();
```
2. forEach
```suggestion
      List<Event> events = List();
      (json["data"] as List).forEach((e) => events.add(Event.fromJson(e)));
```

**Review by werainkhatri — CHANGES_REQUESTED** [review]

File: lib/screens/events/events.dart (hunk 1 above)
Comment (TreavVasu) [reply lib/screens/events/events.dart:36]: Had a talk with him (Mohit) yesterday he said he is working on it.

**Review by werainkhatri — APPROVED** [review]
